# -*- coding: utf-8 -*-
"""FinalAIM460.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WPuuy3eL2HYF9On5IvpSfEOI69JSSkMS

Champions League 2023–24: Predicting Stage with Machine Learning

This notebook uses the 2023–24 Champions League team statistics to predict how far each team advances in the tournament. It includes data cleaning, model training, and comparison between Random Forest, Logistic Regression, and XGBoost models.

I imported the necessary libraries and downloaded the dataset. The printouts help confirm the path and ensure the files were downloaded correctly.
"""

import kagglehub
path = kagglehub.dataset_download("michals22/champions-league-seasons-19911992-20232024")
print("Path to dataset files:", path)

import os

for f in os.listdir(path):
    if f.endswith(".csv"):
        print(f)

import pandas as pd

# Load the group stage data first
group_path = path + "/group_stage.csv"
df = pd.read_csv(group_path)

print("Rows:", len(df))
print("Columns:", list(df.columns)[:15])  # show first 15 columns
df.head()

# Reload with semicolon delimiter
df = pd.read_csv(group_path, delimiter=';')

print("Rows:", len(df))
print("Columns:", list(df.columns))
df.head()

# Try another dataset to find actual match-level data
knock_path = path + "/knock_out_stage.csv"
df_knock = pd.read_csv(knock_path, delimiter=';')

print("Rows:", len(df_knock))
print("Columns:", list(df_knock.columns))
df_knock.head()

# Check if 'seasons.csv' contains match-level data
season_path = path + "/seasons.csv"
df_season = pd.read_csv(season_path, delimiter=';')

print("Rows:", len(df_season))
print("Columns:", list(df_season.columns))
df_season.head(10)

import kagglehub

path = kagglehub.dataset_download("sharvagya/champions-league-2324")
print("Path to dataset files:", path)

import os

for f in os.listdir(path):
    if f.endswith(".csv"):
        print(f)

import os

for root, dirs, files in os.walk(path):
    print("📂 Folder:", root)
    for name in files:
        print("   └──", name)

"""I load the Excel file, check the sheet names, and preview a few rows to understand the dataset’s structure and which columns will be useful"""

import pandas as pd

excel_path = path + "/ChampionsLeague.xlsx"

# Show sheet names to see what’s inside the Excel workbook
xls = pd.ExcelFile(excel_path)
print("Sheets found:", xls.sheet_names)

# Load the first sheet to preview it
df = pd.read_excel(xls, sheet_name=xls.sheet_names[0])
print("Rows:", len(df))
print("Columns:", list(df.columns)[:10])
df.head()

"""I make a clean copy of the data, create a new “Stage” label for each tournament level, drop unnecessary columns, remove missing rows, and encode the target variable for modeling."""

# Copy dataset to a clean version
data = df.copy()

# Simplify target variable (Rk column marks stage: F, SF, QF, etc.)
data["Stage"] = data["Rk"].map({
    "F": "Final",
    "SF": "Semifinal",
    "QF": "Quarterfinal",
    "R16": "Round16",
    "GS": "GroupStage"
})

# Drop unnecessary columns
data = data.drop(columns=["S.N", "Rk", "Squad", "Last 5", "Top Team Scorer", "Goalkeeper", "Country"], errors="ignore")

# Drop missing rows
data = data.dropna()

print("Rows after cleaning:", len(data))
print("Columns:", list(data.columns))

# Encode categorical target
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["Stage_encoded"] = le.fit_transform(data["Stage"])

# Show sample
data.head()

"""I split the data into training and testing sets, train a Random Forest model, and check the results.  
The confusion matrix shows which stages were predicted correctly, and the feature-importance chart highlights which team statistics had the biggest impact.
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Features (all numeric performance stats)
X = data.drop(columns=["Stage", "Stage_encoded"])
y = data["Stage_encoded"]

# Split dataset (75% train, 25% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Train Random Forest model
rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(X_train, y_train)

# Predictions
y_pred = rf.predict(X_test)

# Evaluation
print("=== Classification Report ===")
print(classification_report(y_test, y_pred))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Random Forest Confusion Matrix")
plt.show()

# Feature importance
feat_imp = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)
print("\n=== Feature Importance ===")
print(feat_imp)

plt.figure(figsize=(8,4))
sns.barplot(x=feat_imp, y=feat_imp.index)
plt.title("Feature Importance (Random Forest)")
plt.show()

"""After training the first model, I compare three different algorithms — Random Forest, Logistic Regression, and XGBoost — to see which performs best.  
I scale the data for Logistic Regression and use a stratified split so each class is represented fairly in training and testing.  
Finally, I print the accuracy of each model and look at which one predicts the tournament stages most accurately.
"""

!pip install xgboost scikit-learn --quiet

# === Model comparison with clean label encoding, stratified split, scaling, and warnings handled ===
!pip -q install xgboost

import numpy as np, pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
import matplotlib.pyplot as plt

# X = features, y = your stage labels (text), then encode to 0..K-1 for XGB
X = data.drop(columns=["Stage","Stage_encoded"])
y_text = data["Stage"].astype(str)

le_y = LabelEncoder()
y = le_y.fit_transform(y_text)   # ensures classes are 0..K-1

# Stratified split so every class appears in train/test if possible
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

# Scale for Logistic Regression
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s  = scaler.transform(X_test)

# 1) Random Forest
rf = RandomForestClassifier(n_estimators=300, random_state=42)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
rf_acc = accuracy_score(y_test, rf_pred)

# 2) Logistic Regression (scaled)
log = LogisticRegression(max_iter=2000, solver="liblinear", multi_class="auto")
log.fit(X_train_s, y_train)
log_pred = log.predict(X_test_s)
log_acc = accuracy_score(y_test, log_pred)

# 3) XGBoost (labels now 0..K-1)
xgb = XGBClassifier(
    objective="multi:softmax",
    num_class=len(np.unique(y)),
    eval_metric="mlogloss",
    random_state=42,
    n_estimators=500,
    max_depth=3,
    learning_rate=0.08,
    subsample=0.9,
    colsample_bytree=0.9
)
xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)
xgb_acc = accuracy_score(y_test, xgb_pred)

print("Accuracies:")
print(f"  Random Forest:       {rf_acc:.2f}")
print(f"  Logistic Regression: {log_acc:.2f}")
print(f"  XGBoost:             {xgb_acc:.2f}")

# Pick best model
models = {"RF": (rf, rf_pred), "LR": (log, log_pred), "XGB": (xgb, xgb_pred)}
best_name = max(models, key=lambda k: accuracy_score(y_test, models[k][1]))
best_model, best_pred = models[best_name]

print("\n=== Classification Report (best: " + best_name + ") ===")
print(classification_report(y_test, best_pred, target_names=le_y.classes_, zero_division=0))

# Confusion matrix for best model
cm = confusion_matrix(y_test, best_pred)
plt.figure(figsize=(5,4))
plt.imshow(cm, aspect="auto")
plt.title(f"Confusion Matrix — {best_name}")
plt.xlabel("Predicted")
plt.ylabel("True")
for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, cm[i, j], ha="center", va="center")
plt.colorbar()
plt.show()

"""All three models gave about average accuracy because the dataset was small, but they still showed interesting patterns.  
Matches Played (MP), Points (Pts), and Goal Difference (GD) were the stats that mattered most for predicting how far a team would go.  
Expected Goals (xG) and Expected Goal Difference (xGD) also helped show which teams performed better overall.  
Both XGBoost and Random Forest had similar results and handled the data better than Logistic Regression.  
If I had more seasons or detailed match data, the accuracy would probably get much higher.

This project shows that team statistics can be used to predict how far a club might advance in the Champions League.  
The models found that teams with more points, wins, and better goal differences usually move further in the tournament.  
Even with limited data, the results made sense and showed what really affects success.  
In the future, using more seasons and detailed match data like possession and shots could make the predictions more accurate.
"""